### PR TITLE
Account sync and injection for subprotocols (e.g., whisper)

### PR DESCRIPTION
**Pull request by dwhitena**
Adds `addIdentity` into the whisper API in the context of the develop branch.  This implementation differs from the previous dev's implementation in error handling, function naming, and returns.

In addition, the last dev implemented a `createIdentity` method.  In my understanding this is not needed for our purposes and is in fact redundant.  That is, `newIdentity` already creates a key pair and automatically adds it to the whisper keys.  Is there a case where we would want to manually use this `createIdentity` function?  I think if anything we would either use the `newIdentity` function (which is equivalent to `createIdentity` + `addIdentity`) or use an HD wallet along with `addIdentity`.  Plus would returning this private and public pair to the console be less than ideal.  Am I missing something?

Anyway, this is the addIdentity functionality.

```
dwhitena@dirac:go-ethereum$ build/bin/geth -shh -noeth console
I0603 17:42:58.088418 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/dwhitena/.ethereum/chaindata
I0603 17:42:58.095332 ethdb/database.go:169] closed db:/home/dwhitena/.ethereum/chaindata
I0603 17:42:58.095778 p2p/server.go:311] Starting Server
I0603 17:43:00.667708 p2p/discover/udp.go:217] Listening, enode://dcb63a9c4dc6b87e4e9892c962411ff7b095a6a7daf5f28abb4a76b2f32542a6a81b8693d97789bba67861ece59c380cc8a46ea0b23c12a77ba9c2046b149f63@[::]:30303
I0603 17:43:00.667935 whisper/whisper.go:186] Whisper started
I0603 17:43:00.668303 p2p/server.go:554] Listening on [::]:30303
I0603 17:43:00.668491 node/node.go:298] IPC endpoint opened: /home/dwhitena/.ethereum/geth.ipc
instance: Geth/v1.5.0-unstable-fb80a048/linux/go1.6
> shh.
shh._requestManager shh.constructor     shh.hasIdentity     shh.post            
shh.addIdentity     shh.filter          shh.newGroup        shh.version         
shh.addToGroup      shh.getVersion      shh.newIdentity     
> shh.addIdentity('blah')
failed to convert identity to ECDSA: invalid hex string
    at web3.js:3119:20
    at web3.js:6030:15
    at web3.js:4995:36
    at <anonymous>:1:1

> shh.addIdentity('E9873D79C6D87DC0FB6A5778633389F4453213303DA61F20BD67FC233AA33262')
true
```

### CODE REVIEW

**Comment by jarradh** [comment]
Firstly thanks for going ahead with this, good job on addIdentity. Actually I wanted to discuss this with you before implementation, because we might not need these methods at all and yes there is a reason for createIdentity. It's important to understand what we're trying to do.

In general we are discussing _key management_. The big question here is where do we do key management, if you remember on the call we touched this topic with Felix.

To put the two methods, addIdentity and createIdentity, in context of key management - we are letting our application manage the keys;

**createIdentity** creates a keypair in go (leveraging the existing code) and returns the private (and public key or its derived from private key) so our application can manage them.

**addIdentity** reintroduces our managed private key back into Whisper.

**newIdentity**, however, does not allow us to manage the keys. Instead the key is completely hidden from us.

With that in mind we have 2 options before us, we either allow go-ethereum do key management for us (which I would argue is more secure and we can commit upstream) or we manage the keys on our own, which has some advantages, maybe not enough to warrant.

As you can see a Whisper identity is separate from an Ethereum account, even though they are both  ECDSA key pairs. What we're trying to do is use a person's Ethereum account as their identifier on Whisper. So in Status, you can both chat with and send money to the same public key address.  

If you recall on the call yesterday, Felix had mentioned that go-ethereum accounts allow us to extend them with more information. I was thinking if we don't go the route of managing our keys, we could have an '**whisperEnabled**' Boolean value which would introduce the geth account to whisper. This way we not only get the key persistence in Whisper we need but we also leverage the existing account code - we wouldn't have to do key management (except we'll still need to import and export), and we wouldn't need addIdentity/createIdentity methods for Whisper.

_Also_ HD wallet key generation becomes a completely separate issue of generating accounts in go-ethereum. Which would make it much simpler to introduce into the codebase.

The question is what is the best way to introduce this whisperEnabled flag at account creation.

**Comment by dwhitena** [comment]
This makes a lot more sense Jarrad.  As discussed also on slack, our strategy should be:

Ideal: inject whisper identities via geth's internal account management.

Backup: addIdentity/createIdentity for management on the application side.

Aside: HD wallet (which can be addressed later or in parallel)

Let's not merge this in yet.  I can stash these changes or create another "backup" branch with them.  Then we can develop the internal management functionality on this branch.  Do you want to close without merging?

**Comment by dwhitena** [comment]
I just updated this PR with changes need to add whisper enabled data to accounts when an account is created:

```
dwhitena@dirac:go-ethereum$ build/bin/geth account new
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
You can also choose to enable your new account as a Whisper identity.
Enable the new account as a Whisper Identity? [y/N] y
Address: {c044ce81f99605584f00cc6dec3bf8c151bdd177}
```

**Comment by dwhitena** [comment]
Note, still need to add the logic to inject the account as a whisper ID on create or unlock. As such, we will likely need the `injectIdentity` function added in the previous commit.  We may or may not need the `addIdentity` function depending on how we do the injection.  Working on that now.

**Comment by jarradh** [comment]
yes we won't need the JSON-RPC method addIdentity - that is what this approach is solving

**Comment by dwhitena** [comment]
Well, depending on which parts of whisper I have access to from account manager, I may need some kind of "Add Identity" function in addition to the Inject function.  That is, I may only touch the api, not the whisper service itself.  That's what I'm looking into now.

**Comment by jarradh** [comment]
I don't understand the distinction, my understanding that add identity was injecting a keypair into whisper

**Comment by dwhitena** [comment]
The distinction is that `addIdentity` was a method on the public whisper API, whereas `injectIdentity` was a method on the whisper service itself.  `addIdentity` did inject the keypair along with decoding the hex and it used `injectIdentity` to do the injection.  What I'm looking at now is if I can use the inject function directly on unlock (from account manager), or will still need to have a function in the public API.

**Comment by dwhitena** [comment]
Ok guys, these last commits:

1. add an account sync into account manager for syncing accounts to subprotocols
2. implements the sync for whisper identities on unlock/create
3. modifies the account keystore to store an enabled flag for account synced to whisper
4. modifies the encrypted keystore to store the enabled flag
5. modifies the hasIdentity function to work with addresses or public keys

Thus, you can create an internal geth account, choose to enable that account for whisper, and, upon unlock, the address will be injected in whisper as an identity.

```
dwhitena@dirac:go-ethereum$ build/bin/geth account new
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
You can also choose to enable your new account as a Whisper identity.
Enable the new account as a Whisper Identity? [y/N] y
Address: {705284ffebf7de81d5ba4bfdafa449ee5016a56e}
dwhitena@dirac:go-ethereum$ 
dwhitena@dirac:go-ethereum$ 
dwhitena@dirac:go-ethereum$ 
dwhitena@dirac:go-ethereum$ build/bin/geth --light --shh console
I0607 09:08:22.905939 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/dwhitena/.ethereum/chaindata
I0607 09:08:22.935291 ethdb/database.go:169] closed db:/home/dwhitena/.ethereum/chaindata
I0607 09:08:22.936697 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/dwhitena/.ethereum/chaindata
I0607 09:08:22.954147 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/dwhitena/.ethereum/dapp
I0607 09:08:22.958435 light/lightchain.go:141] Last header: #26688 [486883fc…] TD=17670603983400860
I0607 09:08:22.958656 p2p/server.go:311] Starting Server
I0607 09:08:25.455343 p2p/discover/udp.go:217] Listening, enode://dcb63a9c4dc6b87e4e9892c962411ff7b095a6a7daf5f28abb4a76b2f32542a6a81b8693d97789bba67861ece59c380cc8a46ea0b23c12a77ba9c2046b149f63@[::]:30303
I0607 09:08:25.455498 whisper/whisper.go:190] Whisper started
I0607 09:08:25.455641 p2p/server.go:554] Listening on [::]:30303
I0607 09:08:25.456291 node/node.go:298] IPC endpoint opened: /home/dwhitena/.ethereum/geth.ipc
instance: Geth/v1.5.0-unstable-4c6bdd68/linux/go1.6
> 
> 
> personal.unlockAccount("705284ffebf7de81d5ba4bfdafa449ee5016a56e", "badpassword")
true
> 
> 
> shh.hasIdentity("705284ffebf7de81d5ba4bfdafa449ee5016a56e")
true
> 
```

**Comment by dwhitena** [comment]
I transitioned the injection of the "address" back to injection of the public key as the whisper identity (as is necessitated for sending/receiving messages).  I testing this locally, but please confirm:

```
> 
> personal.unlockAccount("705284ffebf7de81d5ba4bfdafa449ee5016a56e", "badpassword")
Injected identity into whisper: 0x0486e05fc15fcac792e8a7dd862476c03a7b62a3c30eb0dc1abb84ca25cf6ff64d3eea36e94dbc80c3eb847956a5cd6bb2b312dff6b23318903c2adfd28ab281d6
true
> 
> 
> 
> {4dbc80c3eb847956a5cd6bb2b312dff6b23318903c2adfd28ab281d6", "topic": "Hello", "payload": "World"})
true
> {4dbc80c3eb847956a5cd6bb2b312dff6b23318903c2adfd28ab281d6", "topic": "Hello", "payload": "World"})
true
> 
```

**Comment by jarradh** [comment]
this isn't required anymore

**Pull request merged**
