### PR TITLE
track running services for account injection

### PR DESCRIPTION
**Pull request by dwhitena**
Just a small change to return the account sync object I created.  This is necessary for the unlock bindings and possibly other things.

### CODE REVIEW

**Comment by dwhitena** [comment]
Making a few changes here.  Please wait to merge.

**Comment by jarradh** [comment]
will only merge when it's labeled ready :) @rasom  labelled it as in progress for you :)

**Comment by dwhitena** [comment]
Ok, changes made.

**Comment by jarradh** [comment]
please assign to be and change the label to 'ready' when you want me to look at a PR

**Pull request merged**
