### PR TITLE
Apply `0015-geth-17-use-whisperv6.patch`. Part of #status-go/638

### PR DESCRIPTION
**Pull request by PombeirP**
Part of https://github.com/status-im/status-go/issues/638

### CODE REVIEW

**Comment by PombeirP** [comment]
@JekaMas is it OK to merge this PR?

**Comment by themue** [comment]
Did you take a look at the failing build? Is there any dependency failing?

**Comment by PombeirP** [comment]
@themue from what I heard, unfortunately these tests have been broken for a long time.

**Comment by themue** [comment]
Oh, okay, so different reason. AFAIK one import fails.

**Pull request closed without merging**
